### ISSUE TITLE
o.maxplatform object not instantiating

### ISSUE THREAD

**Issue by ghost** [CNMAT/CNMAT-ODOT-SS#20]
I can't seem to find this object in the odot repository (on my computer and on CNMAT downloads). Help!
![screen shot 2018-09-12 at 7 58 01 am](https://user-images.githubusercontent.com/25262418/45433934-1890e780-b662-11e8-8d2e-da2c7abd311c.png)

**Comment by equilet** [comment]
Hi Jason - this is the wrong repository for this issue - I'll be around CNMAT today to help you find the right one, but in general, you need to file issues in a repository germaine to the code they arise from.

**Comment by equilet** [comment]
also worth mentioning that Rama should not be directly assigned in any issue thread - you can assign to either Edmund or myself, then we can reassign.  There are a few key cases in which we should reassign to him, but this is based on evaluation at the time by staff.

**Comment by ramagottfried** [comment]
Hi Jason!
That looks like it might be part of the Esplora patches which aren’t in the odot release. Might be in Music&Computing? Or check with @equilet ?
Best
Rama

Sent via satellite

**Comment by equilet** [comment]
It's a part of MMJSS legacy materials and a couple of other cases, but not the odot release
